name: flutter_belajar
version: 1.0.0+1
description: A new Flutter project.
environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3
  http: ^1.2.1
  shared_preferences: ^2.2.3
  fl_chart: ^0.67.0
  charts_flutter_new: ^0.12.0
  flutter_fusioncharts: ^1.0.2
  speedometer: ^1.1.2
  syncfusion_flutter_gauges: ^21.2.4
  
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  local_auth: ^2.2.0
  google_fonts: ^6.2.0
  syncfusion_flutter_charts: ^21.2.4
  chart_sparkline: ^1.0.15+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_pagination: ^0.0.8
  flutter_speed_dial: ^7.0.0
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  quick_interact: ^1.0.1
  gridview_menu: ^1.0.6
  flutter_draggable_gridview: ^0.0.12
  tab_container: ^3.5.3
  flutter_local_notifications: ^17.1.2
  web_socket_channel: ^3.0.0
  fkafka: ^2.0.1
  permission_handler: ^10.4.5
  flutter_downloader: ^1.11.7
  audioplayers: ^6.0.0
  flutter_background_service: ^5.0.5
  url_launcher: ^6.0.17
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "path/to/image.png"

  

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/kafka.properties
    - assets/sounds/custom_sound.mp3

